### ISSUE TITLE
Deprecated Endpoints

### ISSUE THREAD

**Issue by DingosGotMyBaby** [Tene21/Twitchcord#2]
Hi there,
Just wondering if there was an updated version of this application, given that Twitch's WebSub endpoint was replaced with the EventSub endpoint in 2021 and if there is any other doco for this?

Thanks,
Dingo

**Comment by Tene21** [comment]
Hi, I'm in the process of rewriting the part that handles auto-subscriptions since the switch to EventSub no longer means they have to be renewed regularly. Didn't want to leave the user having to subscribe manually via direct HTTP POST. I'll try and get that done soon and push an update that'll bring this in line with the new endpoints.

**Comment by Tene21** [comment]
That's it updated to EventSub, should check the list of users on startup and auto-subscribe to `channel.update`, `stream.online` and `stream.offline` for any users who're not fully subscribed.

**Comment by DingosGotMyBaby** [comment]
You're a fucking legend! Thank you very much
